### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by shahzad1** [AgoraIO-Community/TokenServer-nodejs#11]
Whenever I try to deploy and enters the APP_ID and APP_CERTIFICATE, it shows me this message
** Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.**

**Comment by plutoless** [comment]
@shahzad1 this looks like a heroku issue.
please read this thread for potential solutions
https://github.com/developeranaz/Mega-index-heroku/issues/28

**Comment by ArcherEmiya05** [comment]
@plutoless having the same issue, is it okay if you update the template here and in the official [doc](https://www.agora.io/en/blog/2-click-setup-testing-token-server/)? We are having a presentation tomorrow and Agora is one of the main feature we need to deliver. Already have a previous project thus all I need is to finish the setup. Thanks
