### ISSUE TITLE
Deploy error on heroku

### ISSUE THREAD

**Issue by Awaissaikhu-577** [AgoraIO-Community/TokenServer-nodejs#2]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy
<img width="389" alt="Screenshot 2022-01-08 at 9 18 26 PM" src="https://user-images.githubusercontent.com/97353271/148651601-5149d71b-9b2d-4dc7-8e98-a953efb308d3.png">
.

**Comment by paul-matthews-dev** [comment]
I'm getting the same. Can this be resolved?

**Comment by Awaissaikhu-577** [comment]
Yup i solved it
